name: Showcase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          declare -a showcase=(
            "ls"
            "date"
          )
          for command in "${showcase[@]}"; do
            ( 
              echo "```shell"
              echo "\$ ${command}"
              ${command}
              echo "```"
            ) > SHOWCASE.md
          done
          curl \
            -X PUT \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token %GITHUB_ACCESS_TOKEN%" \
            -L "https://api.github.com/repos/francescobianco/shell-output-guidelines/SHOWCASE.md" 
            -d "{\"message\":\"Showcase update\",\"content\":\"$(base64 SHOWCASE.md)\"}"
