name: Showcase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          SHOWCASE=$(cat << EOF
          ls
          date
          EOF
          )          
          while IFS= read -r command; do
            echo "\`\`\`shell" >> SHOWCASE.md
            echo "\$ ${command}" >> SHOWCASE.md
            ${command} >> SHOWCASE.md 2>&1 
            echo "\`\`\`" >> SHOWCASE.md
          done <<< "$SHOWCASE"
          echo curl -sLX PUT https://api.github.com/repos/francescobianco/shell-output-guidelines/contents/SHOWCASE.md \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"message\":\"Showcase update\",\"content\":\"$(base64 SHOWCASE.md)\",\"sha\":\"$(git ls-files -s SHOWCASE.md | cut -c8-47)\"}"
