name: Showcase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          SHOWCASE=$(cat << EOF
          ./get-bpkg.sh
          bpkg install qzb/is.sh
          ./deps/bin/is --help
          EOF
          )
          curl -sLo get-bpkg.sh http://get.bpkg.sh/
          chmod +x get-bpkg.sh
          bash get-bpkg.sh
          bpkg install javanile/sharp@main 
          echo "# Showcase" > SHOWCASE.md
          echo "This file collect a lot of real output useful to perform guidelines study" >> SHOWCASE.md
          while IFS= read -r command; do
            echo "\`\`\`" >> SHOWCASE.md
            echo "\$ ${command}" >> SHOWCASE.md
            ${command} > output 2>&1 && true
            cat output | ./deps/bin/sharp >> SHOWCASE.md
            echo "? $?" >> SHOWCASE.md
            echo "\`\`\`" >> SHOWCASE.md
          done <<< "$SHOWCASE"
          curl -sLX PUT https://api.github.com/repos/francescobianco/shell-output-guidelines/contents/SHOWCASE.md \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"message\":\"Update SHOWCASE.md\",\"content\":\"$(base64 -w0 SHOWCASE.md)\",\"sha\":\"$(git ls-files -s SHOWCASE.md | cut -c8-47)\"}"
