name: Showcase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          SHOWCASE=$(cat << EOF
          ls
          date
          EOF
          )          
          while IFS= read -r command; do
            echo "$command"
          done <<< "$SHOWCASE"
