name: Showcase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          SHOWCASE=$(cat << EOF
          curl -Lo setup-bpkg.sh http://get.bpkg.sh/
          bash setup-bpkg.sh
          rm -f setup-bpkg.sh
          bpkg install umq -g
          ump --help
          EOF
          )
          echo "# Showcase" > SHOWCASE.md
          echo "This file collect a lot of real output useful to perform guidelines study" >> SHOWCASE.md
          while IFS= read -r command; do
            echo "\`\`\`" >> SHOWCASE.md
            echo "\$ ${command}" >> SHOWCASE.md
            ${command} | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' > output 2>&1 && true
            cat output >> SHOWCASE.md
            echo "? $?" >> SHOWCASE.md
            echo "\`\`\`" >> SHOWCASE.md
          done <<< "$SHOWCASE"
          cat SHOWCASE.md
          curl -sLX PUT https://api.github.com/repos/francescobianco/shell-output-guidelines/contents/SHOWCASE.md \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"message\":\"Update SHOWCASE.md\",\"content\":\"$(base64 -w0 SHOWCASE.md)\",\"sha\":\"$(git ls-files -s SHOWCASE.md | cut -c8-47)\"}"
